name: Update Emergency Data

on:
  schedule:
    - cron: '0 0 * * 0'   # Every Sunday at 00:00 UTC
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have a requirements.txt:
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run data/web-scrap.py to update data/data.json
      run: python data/web-scrap.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/data.json
        git diff --quiet && echo "No changes to commit" || (git commit -m "Auto update data.json" && git push)
